In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

df = pd.read_csv('https://raw.githubusercontent.com/delinai/schulich_ds1/refs/heads/main/Datasets/kc_house_data.csv')

In [18]:
x = df.iloc[:,3:]
y = df['price']
x = sm.add_constant(x)

In [19]:
model_houses = sm.OLS(y,x).fit()

In [20]:
x.columns

Index(['const', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [21]:
x = x.iloc[:,1:]

In [22]:
housing_lasso = lm.Lasso(alpha=10).fit(x,y)
housing_lasso.coef_

c:\Users\q\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.986e+14, tolerance: 2.913e+11
  model = cd_fast.enet_coordinate_descent(


array([-3.57559842e+04,  4.11108709e+04,  2.84818067e+02,  1.28219702e-01,
        6.67928397e+03,  5.81445656e+05,  5.29220812e+04,  2.63513732e+04,
        9.59170369e+04, -1.03584377e+02, -1.34664906e+02, -2.62150608e+03,
        1.98221202e+01, -5.81031778e+02,  6.02100539e+05, -2.13835108e+05,
        2.16525206e+01, -3.83132258e-01])

In [14]:
x = x.iloc[:,1:]

In [23]:
housing_lasso = lm.Lasso(alpha=10000).fit(x,y)
housing_lasso.coef_

c:\Users\q\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.348e+14, tolerance: 2.913e+11
  model = cd_fast.enet_coordinate_descent(


array([-2.16013795e+04,  0.00000000e+00,  2.74119952e+02, -2.22627361e-02,
        0.00000000e+00,  0.00000000e+00,  5.48269200e+04,  0.00000000e+00,
        1.05906121e+05, -7.74626262e+01, -8.37003127e+01, -3.03919501e+03,
        2.65113813e+01,  7.83962080e+01,  0.00000000e+00, -0.00000000e+00,
        2.85042097e+01, -5.91213109e-01])

In [24]:
model_ridge = lm.Ridge(alpha=10).fit(x,y)
model_ridge.coef_

array([-3.60298219e+04,  4.11642884e+04,  1.10604846e+02,  1.22108123e-01,
        7.40946808e+03,  5.42743185e+05,  5.44497507e+04,  2.62150268e+04,
        9.64523666e+04,  7.04043311e+01,  4.02004676e+01, -2.64913748e+03,
        1.99895480e+01, -5.63133495e+02,  5.85465595e+05, -2.05287713e+05,
        2.14311629e+01, -3.87374800e-01])

In [27]:
model_ridge = lm.Ridge(alpha=1000000).fit(x,y)
model_ridge.coef_

array([-6.74735408e+02,  2.43101017e+02,  1.65219446e+02,  5.73636731e-02,
        2.41951435e+02,  1.20235044e+02,  9.18172515e+02,  1.88455509e+02,
        1.29455536e+03,  9.22104748e+01,  7.30089714e+01, -2.13159607e+03,
        4.65992462e+01,  3.93249391e+02,  2.42072836e+02, -8.89041797e+01,
        9.65648100e+01, -7.17132615e-01])