In [7]:
import numpy as np

In [1]:
pip install numpy

In [2]:
# common elements of Python
# lists, tuples, sets and dictionaries
# common operations >> conditionals, loops
# numpy operations
# common pandas operations

In [3]:
# lists --> []

list1 = [12, 15, 78, 15, 25]

In [4]:
list1.append(100)
list1

[12, 15, 78, 15, 25, 100]

In [6]:
# when you append a LIST of items you get a nested list
list1.append([100, 200])
list1

[12, 15, 78, 15, 25, 100, [100, 200]]

In [7]:
# combine two lists together using extend()
list1.extend([100,200,300])
list1

[12, 15, 78, 15, 25, 100, [100, 200], 100, 200, 300]

In [9]:
# insert a value at a specific position
list1.insert(2, 1000)
list1

[12, 15, 1000, 78, 15, 25, 100, [100, 200], 100, 200, 300]

In [10]:
# pop() or remove()
list1.pop(7)
list1

[12, 15, 1000, 78, 15, 25, 100, 100, 200, 300]

In [11]:
# remove() --> first time the value occurs
list1.remove(15)

In [12]:
list1

[12, 1000, 78, 15, 25, 100, 100, 200, 300]

In [13]:
# index() tells you the FIRST index position of a value
list1.index(100)

5

In [14]:
# count() will tell you how many of a specific value you have
list1.count(100)

2

In [15]:
# indexing and slicing
list1[0]

12

In [16]:
# slice -- isolate a range of values
list1[3:7]

[15, 25, 100, 100]

In [17]:
# starting position : ending position : step (2 = every other item)
list1[1:8:2]

[1000, 15, 100, 200]

In [18]:
# lists support item assignment meaning we can overwrite values
list1[0] = 4000

In [19]:
list1

[4000, 1000, 78, 15, 25, 100, 100, 200, 300]

In [21]:
# tuple --> defined with round brackets ()
tuple1 = (8, 7, 6, 15)

In [22]:
# count the number of elements of a certain value
tuple1.count(8)

1

In [23]:
# find the first position of a certain value
tuple1.index(15)

3

In [24]:
# find a value in a certain position
tuple1[0]

8

In [25]:
# you cannot overwrite or change values in a tuple
tuple1[0] = 1000

TypeError: 'tuple' object does not support item assignment

In [26]:
# sets --> {}
set1 = {12, 13, 15, 18, 25, 15, 100, 100}

In [27]:
# sets do not hold duplicates, so even if you define one with dupes it will remove them
set1

{12, 13, 15, 18, 25, 100}

In [28]:
set2 = {13, 100, 18, 14, 27, 35}

In [29]:
# find common elements
set1.intersection(set2)

{13, 18, 100}

In [30]:
# find elements that exist in set 1 but NOT in set 2
set1.difference(set2)

{12, 15, 25}

In [31]:
# elements in set2 that don't exist in set1
set2.difference(set1)

{14, 27, 35}

In [32]:
set1

{12, 13, 15, 18, 25, 100}

In [33]:
set2

{13, 14, 18, 27, 35, 100}

In [34]:
# if i only want to keep elements in set2 which are different than set1
set2.difference_update(set1)

In [35]:
set2

{14, 27, 35}

In [39]:
set1.intersection(list1)

{15, 25, 100}

In [40]:
sum(list1)

5818

In [41]:
sum(set1)

183

In [42]:
sum(tuple1)

36

In [43]:
min(list1)

15

In [44]:
max(set2)

35

In [45]:
# dictionaries

dict1 = {'ON': 'Toronto', 'MB': 'Winnipeg', 'SK':'Regina', 'BC':'Victoria'}

In [46]:
# all the keys of the dictionary
dict1.keys()

dict_keys(['ON', 'MB', 'SK', 'BC'])

In [47]:
dict1.values()

dict_values(['Toronto', 'Winnipeg', 'Regina', 'Victoria'])

In [48]:
# hierarchical data example - shopping cart

dict2 = {'customer1':{'books':['book1','book2'],'food':['chips','tomatoes']},'customer2':{'clothing':['socks','shirt'], 'electronics':['tv','computer','ipad']}}

In [49]:
dict2.keys()

dict_keys(['customer1', 'customer2'])

In [50]:
dict2.values()

dict_values([{'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']}, {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'computer', 'ipad']}])

In [52]:
dict2['customer1'].keys()

dict_keys(['books', 'food'])

In [53]:
dict2['customer1'].values()

dict_values([['book1', 'book2'], ['chips', 'tomatoes']])

In [54]:
# adding a new key:value to a dictionary - just add one that doesn't exist
dict2['customer3'] = {'groceries':['chips','pop'], 'shoes':['running shoes', 'tennis shoes']}

In [55]:
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']},
 'customer2': {'clothing': ['socks', 'shirt'],
  'electronics': ['tv', 'computer', 'ipad']},
 'customer3': {'groceries': ['chips', 'pop'],
  'shoes': ['running shoes', 'tennis shoes']}}

In [56]:
# removing an element, we can use pop()
dict2.pop('customer3')

{'groceries': ['chips', 'pop'], 'shoes': ['running shoes', 'tennis shoes']}

In [57]:
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']},
 'customer2': {'clothing': ['socks', 'shirt'],
  'electronics': ['tv', 'computer', 'ipad']}}

In [58]:
dict2.items()

dict_items([('customer1', {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']}), ('customer2', {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'computer', 'ipad']})])

In [72]:
# conditional statements
x = 9*12/14+10

In [74]:
# make sure conditions are mutually exclusive
if x > 10:
  x = (x + 15) / 22
  x = x/12
  print(f'{x} is calculated')
elif x > 5 and x <= 10:
  x = (x +10) / 12
  print(x)

else:
  x = 0


In [77]:
# looping -- the for loop

for i in list1:
  if i > 100:
    i = (i + 15) / 22
    i = i/12
    print(f'{i} is calculated')
  elif i > 5 and i <= 100:
    i = (i +10) / 12
    print(i)
  else:
    i = 0

15.208333333333334 is calculated
3.8446969696969693 is calculated
7.333333333333333
2.0833333333333335
2.9166666666666665
9.166666666666666
9.166666666666666
0.8143939393939394 is calculated
1.1931818181818181 is calculated


In [78]:
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']},
 'customer2': {'clothing': ['socks', 'shirt'],
  'electronics': ['tv', 'computer', 'ipad']}}

In [89]:
# calculate how many items from each major category were ordered
categories_w_purchases = []
items_purchased = []
num_categories = 0
num_items = 0
num_items_by_category = {}

for key, value in dict2.items():
  for a, b in value.items():
    if a not in categories_w_purchases:
      categories_w_purchases.append(a)
      num_categories += 1
    for item in b:
      if item not in items_purchased:
        items_purchased.append(item)
        num_items += 1
      if a not in num_items_by_category.keys():
        num_items_by_category[a] = 1
      else:
        num_items_by_category[a] += 1

print(categories_w_purchases)
print(items_purchased)
print(num_categories)
print(num_items)
print(num_items_by_category)

['books', 'food', 'clothing', 'electronics']
['book1', 'book2', 'chips', 'tomatoes', 'socks', 'shirt', 'tv', 'computer', 'ipad']
4
9
{'books': 2, 'food': 2, 'clothing': 2, 'electronics': 3}


In [86]:
for i in dict2.items():
  print(i)

('customer1', {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']})
('customer2', {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'computer', 'ipad']})


In [90]:
import numpy as np

In [91]:
arr1 = np.array(list1)

In [92]:
arr1

array([4000, 1000,   78,   15,   25,  100,  100,  200,  300])

In [93]:
arr1.mean()

np.float64(646.4444444444445)

In [94]:
arr1.sum()

np.int64(5818)

In [95]:
arr1.astype(float)

array([4000., 1000.,   78.,   15.,   25.,  100.,  100.,  200.,  300.])

In [96]:
arr1[0]

np.int64(4000)

In [97]:
arr1.shape

(9,)

In [102]:
arr1 = np.append(arr1, 500)

In [103]:
arr1.shape

(10,)

In [104]:
arr1.reshape(5,2)

array([[4000, 1000],
       [  78,   15],
       [  25,  100],
       [ 100,  200],
       [ 300,  500]])

In [105]:
arr1.reshape(2,5)

array([[4000, 1000,   78,   15,   25],
       [ 100,  100,  200,  300,  500]])

In [106]:
arr1

array([4000, 1000,   78,   15,   25,  100,  100,  200,  300,  500])

In [107]:
arr2 = np.array([10])

In [108]:
arr1 + arr2

array([4010, 1010,   88,   25,   35,  110,  110,  210,  310,  510])

In [109]:
arr1 * arr2

array([40000, 10000,   780,   150,   250,  1000,  1000,  2000,  3000,
        5000])